// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/customers-data-request": {
    params: {};
  };
  "/webhooks/app/customers-redact": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/shop-redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/api/deleteShipmentFile": {
    params: {};
  };
  "/api/uploadShipmentFile": {
    params: {};
  };
  "/api/billing-subscribe": {
    params: {};
  };
  "/api/shopify/products": {
    params: {};
  };
  "/api/check-ocr-limit": {
    params: {};
  };
  "/api/delete-shipment": {
    params: {};
  };
  "/api/shopify/graphql": {
    params: {};
  };
  "/api/test-connection": {
    params: {};
  };
  "/api/createShipment": {
    params: {};
  };
  "/api/updateShipment": {
    params: {};
  };
  "/api/get-file-url": {
    params: {};
  };
  "/api/test-storage": {
    params: {};
  };
  "/billing/callback": {
    params: {};
  };
  "/api/ocr-health": {
    params: {};
  };
  "/api/sync-stock": {
    params: {};
  };
  "/api/pdf2image": {
    params: {};
  };
  "/api/shipments": {
    params: {};
  };
  "/api/ai-parse": {
    params: {};
  };
  "/api/ocr-text": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/api/usage": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/contact": {
    params: {};
  };
  "/app/pricing": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/customers-data-request" | "/webhooks/app/customers-redact" | "/webhooks/app/scopes_update" | "/webhooks/app/shop-redact" | "/webhooks/app/uninstalled" | "/api/deleteShipmentFile" | "/api/uploadShipmentFile" | "/api/billing-subscribe" | "/api/shopify/products" | "/api/check-ocr-limit" | "/api/delete-shipment" | "/api/shopify/graphql" | "/api/test-connection" | "/api/createShipment" | "/api/updateShipment" | "/api/get-file-url" | "/api/test-storage" | "/billing/callback" | "/api/ocr-health" | "/api/sync-stock" | "/api/pdf2image" | "/api/shipments" | "/api/ai-parse" | "/api/ocr-text" | "/auth/login" | "/api/usage" | "/auth/*" | "/app" | "/app/additional" | "/app/contact" | "/app/pricing";
  };
  "routes/webhooks.app.customers-data-request.jsx": {
    id: "routes/webhooks.app.customers-data-request";
    page: "/webhooks/app/customers-data-request";
  };
  "routes/webhooks.app.customers-redact.jsx": {
    id: "routes/webhooks.app.customers-redact";
    page: "/webhooks/app/customers-redact";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.shop-redact.jsx": {
    id: "routes/webhooks.app.shop-redact";
    page: "/webhooks/app/shop-redact";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/api.deleteShipmentFile.ts": {
    id: "routes/api.deleteShipmentFile";
    page: "/api/deleteShipmentFile";
  };
  "routes/api.uploadShipmentFile.ts": {
    id: "routes/api.uploadShipmentFile";
    page: "/api/uploadShipmentFile";
  };
  "routes/api.billing-subscribe.ts": {
    id: "routes/api.billing-subscribe";
    page: "/api/billing-subscribe";
  };
  "routes/api.shopify.products.ts": {
    id: "routes/api.shopify.products";
    page: "/api/shopify/products";
  };
  "routes/api.check-ocr-limit.js": {
    id: "routes/api.check-ocr-limit";
    page: "/api/check-ocr-limit";
  };
  "routes/api.delete-shipment.ts": {
    id: "routes/api.delete-shipment";
    page: "/api/delete-shipment";
  };
  "routes/api.shopify.graphql.ts": {
    id: "routes/api.shopify.graphql";
    page: "/api/shopify/graphql";
  };
  "routes/api.test-connection.ts": {
    id: "routes/api.test-connection";
    page: "/api/test-connection";
  };
  "routes/api.createShipment.ts": {
    id: "routes/api.createShipment";
    page: "/api/createShipment";
  };
  "routes/api.updateShipment.ts": {
    id: "routes/api.updateShipment";
    page: "/api/updateShipment";
  };
  "routes/api.get-file-url.ts": {
    id: "routes/api.get-file-url";
    page: "/api/get-file-url";
  };
  "routes/api.test-storage.ts": {
    id: "routes/api.test-storage";
    page: "/api/test-storage";
  };
  "routes/billing.callback.tsx": {
    id: "routes/billing.callback";
    page: "/billing/callback";
  };
  "routes/api.ocr-health.ts": {
    id: "routes/api.ocr-health";
    page: "/api/ocr-health";
  };
  "routes/api.sync-stock.ts": {
    id: "routes/api.sync-stock";
    page: "/api/sync-stock";
  };
  "routes/api.pdf2image.ts": {
    id: "routes/api.pdf2image";
    page: "/api/pdf2image";
  };
  "routes/api.shipments.ts": {
    id: "routes/api.shipments";
    page: "/api/shipments";
  };
  "routes/api.ai-parse.ts": {
    id: "routes/api.ai-parse";
    page: "/api/ai-parse";
  };
  "routes/api.ocr-text.ts": {
    id: "routes/api.ocr-text";
    page: "/api/ocr-text";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/api.usage.js": {
    id: "routes/api.usage";
    page: "/api/usage";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/additional" | "/app/contact" | "/app/pricing";
  };
  "routes/app.additional.tsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.contact.tsx": {
    id: "routes/app.contact";
    page: "/app/contact";
  };
  "routes/app.pricing.tsx": {
    id: "routes/app.pricing";
    page: "/app/pricing";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.customers-data-request": typeof import("./app/routes/webhooks.app.customers-data-request.jsx");
  "routes/webhooks.app.customers-redact": typeof import("./app/routes/webhooks.app.customers-redact.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.shop-redact": typeof import("./app/routes/webhooks.app.shop-redact.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/api.deleteShipmentFile": typeof import("./app/routes/api.deleteShipmentFile.ts");
  "routes/api.uploadShipmentFile": typeof import("./app/routes/api.uploadShipmentFile.ts");
  "routes/api.billing-subscribe": typeof import("./app/routes/api.billing-subscribe.ts");
  "routes/api.shopify.products": typeof import("./app/routes/api.shopify.products.ts");
  "routes/api.check-ocr-limit": typeof import("./app/routes/api.check-ocr-limit.js");
  "routes/api.delete-shipment": typeof import("./app/routes/api.delete-shipment.ts");
  "routes/api.shopify.graphql": typeof import("./app/routes/api.shopify.graphql.ts");
  "routes/api.test-connection": typeof import("./app/routes/api.test-connection.ts");
  "routes/api.createShipment": typeof import("./app/routes/api.createShipment.ts");
  "routes/api.updateShipment": typeof import("./app/routes/api.updateShipment.ts");
  "routes/api.get-file-url": typeof import("./app/routes/api.get-file-url.ts");
  "routes/api.test-storage": typeof import("./app/routes/api.test-storage.ts");
  "routes/billing.callback": typeof import("./app/routes/billing.callback.tsx");
  "routes/api.ocr-health": typeof import("./app/routes/api.ocr-health.ts");
  "routes/api.sync-stock": typeof import("./app/routes/api.sync-stock.ts");
  "routes/api.pdf2image": typeof import("./app/routes/api.pdf2image.ts");
  "routes/api.shipments": typeof import("./app/routes/api.shipments.ts");
  "routes/api.ai-parse": typeof import("./app/routes/api.ai-parse.ts");
  "routes/api.ocr-text": typeof import("./app/routes/api.ocr-text.ts");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/api.usage": typeof import("./app/routes/api.usage.js");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.tsx");
  "routes/app.contact": typeof import("./app/routes/app.contact.tsx");
  "routes/app.pricing": typeof import("./app/routes/app.pricing.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
};